Select * from customer limit 20
--Q1. What is the Total Revenue generated by male vs. female customer?

select gender , sum (purchase_amount) as revenue 
from customer
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, 
purchase_amount from customer 
where discount_applied ='Yes' and purchase_amount >=(select AVG(purchase_amount) from customer)

--Q3.Which are the top 5 products with the highest average review rating?
SELECT item_purchased,Round(AVG(review_rating::numeric),2) AS "Average Product Rating"
FROM customer
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

--Q4.Compare the average purchase amounts between standard and express shipping.
select shipping_type, Round(AVG(purchase_amount)::numeric,2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type

--Q5.Do Subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers?
SELECT
    subscription_status,
    COUNT(customer_id) AS total_customer,
    ROUND(AVG(purchase_amount)::numeric, 2) AS average_spend,
    ROUND(SUM(purchase_amount)::numeric, 2) AS total_revenue
FROM customer
GROUP BY subscription_status
ORDER BY total_revenue,average_spend DESC;

--Q6.Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased,Round(100*SUM(Case when discount_applied= 'Yes' Then 1 Else 0 End)/COUNT (*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Q7. Segment customers into New,Returning, and loyal based on their total 
--number of previous purchases,and show the count of each segment?**
with customer_type as 
(select customer_id, previous_purchases,
case when previous_purchases=1 then 'New'
when previous_purchases Between 2 AND 10 Then 'Returning'
else 'Loyal Customer'
END AS Customer_Segment
from customer)

SELECT Customer_segment, count(*) as "Number of Customers"
from customer_type
group by Customer_segment
--Q8.What are the top 3 most purchased products within each category?
with item_counts as (
select category, item_purchased,
count(customer_id) as total_orders,
Row_Number()over(partition by category order by count(customer_id) Desc) as item_rank
from customer
group by category, item_purchased)

select item_rank,category, item_purchased, total_orders 
from item_counts
where item_rank <=3

--Q9.Are customers who are repeat buyers(More than 5 previous purchases) also likely to subscribe?**
select subscription_status, 
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

--Q10.What is the revenue contribution of each age group?
select age_group, sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc
